# Generated by Django 5.2.3 on 2026-06-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_annual_fils', models.BigIntegerField(default=0)),
                ('current_monthly_fils', models.BigIntegerField(default=0)),
                ('market_annual_fils', models.BigIntegerField(default=0)),
                ('market_monthly_fils', models.BigIntegerField(default=0)),
                ('dld_evidence_ref', models.TextField(blank=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_assumed', models.BooleanField(default=True)),
                ('annual_gap_fils', models.BigIntegerField(default=0)),
                ('gap_status', models.CharField(default='at_market', max_length=16)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rentdata', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
