# Generated by Django 5.2.3 on 2026-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_ref', models.CharField(max_length=32, unique=True)),
                ('property_type', models.CharField(choices=[('lx_villa', 'Luxury Villa'), ('std_villa', 'Standard Villa'), ('larger_apt', 'Larger Apartment'), ('std_flat', 'Standard Flat')], max_length=32)),
                ('area', models.CharField(max_length=128)),
                ('bedrooms', models.CharField(blank=True, max_length=32)),
                ('floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value_fils', models.BigIntegerField(default=0)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('valuation_source', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='active', max_length=32)),
                ('occupancy_status', models.CharField(default='vacant', max_length=32)),
                ('vacancy_start_date', models.DateField(blank=True, null=True)),
                ('target_occupancy_date', models.DateField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_assumed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['unit_ref'],
            },
        ),
    ]
