# Generated by Django 5.2.3 on 2026-06-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed per unit')], default='percent', max_length=16)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=5.8, max_digits=5)),
                ('fixed_fee_fils', models.BigIntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('is_assumed', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.CharField(choices=[('bear', 'Bear'), ('base', 'Base'), ('bull', 'Bull')], max_length=16, unique=True)),
                ('occupancy_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rent_correction_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('growth_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_assumed', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('scenario', models.CharField(choices=[('current', 'Current'), ('potential', 'Potential'), ('bear', 'Bear')], max_length=16)),
                ('amount_fils', models.BigIntegerField(default=0)),
                ('is_assumed', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('year', 'month', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioYearProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_index', models.IntegerField()),
                ('revenue_fils', models.BigIntegerField(default=0)),
                ('is_assumed', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='financials.scenarioconfig')),
            ],
            options={
                'unique_together': {('scenario', 'year_index')},
            },
        ),
    ]
